In [1]:
import pandas as pd
df = pd.read_csv("../data/Cleaned_Superstore.csv")

In [2]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [3]:
# which category generates the highest total sales?
sales_by_category = df.groupby("Category")["Sales"].sum()
sales_by_category

Category
Furniture          741306.3133
Office Supplies    718735.2440
Technology         836154.0330
Name: Sales, dtype: float64

In [4]:
# which category generates the highest total profit?
sales_by_category = df.groupby("Category")["Profit"].sum()
sales_by_category

Category
Furniture           18421.8137
Office Supplies    122364.6608
Technology         145454.9481
Name: Profit, dtype: float64

In [5]:
# which region generates the highest sales?
sales_by_region = df.groupby("Region")["Sales"].sum()
sales_by_region

Region
Central    500782.8528
East       678435.1960
South      391721.9050
West       725255.6365
Name: Sales, dtype: float64

In [6]:
# which region generates the highest profit?
sales_by_region = df.groupby("Region")["Profit"].sum()
sales_by_region

Region
Central     39655.8752
East        91506.3092
South       46749.4303
West       108329.8079
Name: Profit, dtype: float64

In [7]:
sales_by_segment = df.groupby("Segment")["Sales"].sum()     # sales by segment

In [8]:
sales_by_segment

Segment
Consumer       1.160833e+06
Corporate      7.060701e+05
Home Office    4.292927e+05
Name: Sales, dtype: float64

In [9]:
category_analysis = df.groupby("Category").agg(
    Total_sales = ('Sales','sum'),
    Total_profit = ('Profit','sum'),
    Average_sales = ('Sales','mean'),
    Average_profit = ('Profit','mean')
)

category_analysis

                 Total_sales  Total_profit  Average_sales  Average_profit
Category
Furniture        741306.3133    18421.8137     350.002981        8.697740
Office Supplies  718735.2440   122364.6608     119.550107       20.353403
Technology       836154.0330   145454.9481     452.709276       78.752002

In [11]:
# Find the best category

category_analysis.sort_values(
    by="Total_profit",
    ascending=False
)

                 Total_sales  Total_profit  Average_sales  Average_profit
Category
Technology       836154.0330   145454.9481     452.709276       78.752002
Office Supplies  718735.2440   122364.6608     119.550107       20.353403
Furniture        741306.3133    18421.8137     350.002981        8.697740