In [1]:
import pandas as pd
df = pd.read_csv("../data/Cleaned_Superstore.csv")

In [2]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [3]:
df.columns

Index(['Ship Mode', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Category', 'Sub-Category', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [5]:
# which sub category generates the highest sales?
sales_by_subcategory = df.groupby(
    "Sub-Category"
)["Sales"].sum().sort_values(
    ascending = False
)

sales_by_subcategory

Sub-Category
Phones         330007.0540
Chairs         327777.7610
Storage        223843.6080
Tables         206965.5320
Binders        203409.1690
Machines       189238.6310
Accessories    167380.3180
Copiers        149528.0300
Bookcases      114879.9963
Appliances     107532.1610
Furnishings     91683.0240
Paper           78224.1420
Supplies        46673.5380
Art             27107.0320
Envelopes       16476.4020
Labels          12444.9120
Fasteners        3024.2800
Name: Sales, dtype: float64

In [7]:
# which sub category generates the highest profit?

profit_by_subcategory = df.groupby(
    "Sub-Category"
)["Profit"].sum().sort_values(
    ascending = False
)

profit_by_subcategory

Sub-Category
Copiers        55617.8249
Phones         44515.7306
Accessories    41936.6357
Paper          33944.2395
Binders        30228.0003
Chairs         26567.1278
Storage        21278.8264
Appliances     18138.0054
Furnishings    13052.7230
Envelopes       6964.1767
Art             6524.6118
Labels          5526.3820
Machines        3384.7569
Fasteners        949.5182
Supplies       -1189.0995
Bookcases      -3472.5560
Tables        -17725.4811
Name: Profit, dtype: float64

In [9]:
# Analyze quantity
# which sub category has the highest quantity sold ?

quantity_by_subcategory = df.groupby(
    "Sub-Category"
)["Quantity"].sum().sort_values(
    ascending = False
)

quantity_by_subcategory

Sub-Category
Binders        5971
Paper          5144
Furnishings    3560
Phones         3289
Storage        3158
Art            2996
Accessories    2976
Chairs         2351
Appliances     1729
Labels         1396
Tables         1241
Fasteners       914
Envelopes       906
Bookcases       868
Supplies        647
Machines        440
Copiers         234
Name: Quantity, dtype: int64

In [10]:
# Create a complete sub category analysis

subcategory_analysis = df.groupby(
    "Sub-Category"
).agg(
    Total_sales = ("Sales",'sum'),
    Total_profit = ('Profit','sum'),
    Total_quantity = ('Quantity','sum'),
    Average_discount = ("Discount",'mean')
).sort_values(
    by = 'Total_profit',
    ascending = False
)

subcategory_analysis

              Total_sales  Total_profit  Total_quantity  Average_discount
Sub-Category
Copiers       149528.0300    55617.8249             234          0.161765
Phones        330007.0540    44515.7306            3289          0.154556
Accessories   167380.3180    41936.6357            2976          0.078452
Paper          78224.1420    33944.2395            5144          0.074908
Binders       203409.1690    30228.0003            5971          0.372011
Chairs        327777.7610    26567.1278            2351          0.170244
Storage       223843.6080    21278.8264            3158          0.074704
Appliances    107532.1610    18138.0054            1729          0.166524
Furnishings    91683.0240    13052.7230            3560          0.138494
Envelopes      16476.4020     6964.1767             906          0.080315
Art            27107.0320     6524.6118            2996          0.074969
Labels         12444.9120     5526.3820            1396          0.068871
Machines      189238.6310     3384.7569             440          0.306087
Fasteners       3024.2800      949.5182             914          0.082028
Supplies       46673.5380    -1189.0995             647          0.076842
Bookcases     114879.9963    -3472.5560             868          0.211140
Tables        206965.5320   -17725.4811            1241          0.261285